"""phone number off

Revision ID: 64667aaf9954
Revises: c862ddfaf8d3
Create Date: 2024-07-23 19:53:28.065900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64667aaf9954'
down_revision: Union[str, None] = 'c862ddfaf8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if the column already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'phone_number' not in [col['name'] for col in inspector.get_columns('users')]:
        op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
